name: 勉強会説明用フォーム
description: 勉強会で紹介するフォーム
title: "titleデフォルト値設定可能"
labels: ["01_子Issue"]
body:
  - type: markdown
    attributes:
      value: |
        ↓自由にマークダウンを書くことができます↓
        ---
        # Header1
        ## Header2
        ### Header3
        1. cl
          1. cl
            1. cl
            1. cl
          1. cl
        1. cl
        - ul
          - ul
            - ul
            - ul
          - ul
        - ul
        ---
        ↑自由にマークダウンを書くことができます↑
        入力系のタグのドキュメントは [GitHub Docs](https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#textarea)からも確認できます。
  - type: checkboxes
    id: check01
    attributes:
      label: checkboxes
      description: チェックボックスを配置することができます
      options:
        - label: この内容が公開されることに同意します
          required: true
  - type: checkboxes
    id: check02
    attributes:
      label: checkboxes (複数)
      description: チェックボックスを複数指定することもできます
      options:
        - label: 抵抗制御
        - label: チョッパ制御
        - label: 界磁添加励磁制御
        - label: サイリスタ位相制御
        - label: VVVFインバータ制御
  - type: dropdown
    id: dr01
    attributes:
      label: dropdown
      description: ドロップダウンを配置することができます
      options:
        - SE
        - NSE
        - LSE
        - HiSE
        - RSE
        - EXE
        - VSE
        - MSE
        - GSE
    validations:
      required: true
  - type: dropdown
    id: dr02
    attributes:
      label: dropdown (複数選択)
      description: ドロップダウンで複数の値を指定することもできます
      multiple: true
      options:
        - "1000"
        - "2000"
        - "3000"
        - "4000"
        - "5000"
        - "8000"
  - type: input
    id: input01
    attributes:
      label: input
      description: １行の文字列を入力する場合はinputを使います
  - type: textarea
    id: textarea1
    attributes:
      label: textarea
      description: 複数行の文字列を入力する場合はtextareaを使います
